### ISSUE TITLE
How to use? Please consider write a Readme.md

### ISSUE THREAD

**Issue by linonetwo** [thomashorrobin/create-react-app-rust#1]
Is this an out-of-box solution for use rust in CRA?

**Comment by thomashorrobin** [comment]
yeah, it is. I basically wanted to combine a number of cool things that are going on with the Rust compiler and WebAssembly into a CRA fork. At this stage it's mainly an experimental/demo thing.

I was inspired by these:
- https://users.rust-lang.org/t/native-webassembly-loader-for-webpack/14407
- https://github.com/yamafaktory/rust-wasm-webpack
- https://www.hellorust.com/demos/add/index.html

Unfortunately it's not really going to work the way I want it to until Webpack 4 is merged into master in the upstream CRA project. 

However it is kinda working with Webpack 3.8.1 and I've added a few notes to the README to explain how to do it. I always appreciate feedback if you wanted to have another go 🙂👍. Also, I always appreciate PRs 🎉

**Comment by Terkwood** [comment]
Hey, just want to leave a happy note here. I tried following the instructions in the README... and it worked! Thanks! 🕺 

I spent a lot of time trying to figure out how to do this, before I found your work! 😁

**Comment by thomashorrobin** [comment]
Thanks @Terkwood, I'm glad someone found it useful!!

And thanks for the PR!
